# Generated by Django 5.0.3 on 2024-03-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatemodel',
            old_name='phone_numbee',
            new_name='phone_number',
        ),
    ]
